project_id          = "ENTER_YOUR_PROJECT_ID_HERE"
region              = "us-west4"
service_name        = "memoria-spanner"
spanner_instance_id = "memoria-spanner-inst"
spanner_database_id = "memoria-spanner-db"
